// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhH2et7ogSzE5NX4sNssUiJ6q5nqrTQpA',
    appId: '1:864533928664:web:c686f25a1da9a0df7155ad',
    messagingSenderId: '864533928664',
    projectId: 'to-do-list-c9aaf',
    authDomain: 'to-do-list-c9aaf.firebaseapp.com',
    storageBucket: 'to-do-list-c9aaf.firebasestorage.app',
    measurementId: 'G-LDZY27F08P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_pI8MEtmBK1zugH3ol6SxNJ436GvuwOQ',
    appId: '1:864533928664:android:374f5dca0ad774797155ad',
    messagingSenderId: '864533928664',
    projectId: 'to-do-list-c9aaf',
    storageBucket: 'to-do-list-c9aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6D-MP8H1z6n_tCv0_bg0CZuYmD8VD9vU',
    appId: '1:864533928664:ios:9ec82ece056720d27155ad',
    messagingSenderId: '864533928664',
    projectId: 'to-do-list-c9aaf',
    storageBucket: 'to-do-list-c9aaf.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6D-MP8H1z6n_tCv0_bg0CZuYmD8VD9vU',
    appId: '1:864533928664:ios:9ec82ece056720d27155ad',
    messagingSenderId: '864533928664',
    projectId: 'to-do-list-c9aaf',
    storageBucket: 'to-do-list-c9aaf.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhH2et7ogSzE5NX4sNssUiJ6q5nqrTQpA',
    appId: '1:864533928664:web:0e2e52800c93fe0d7155ad',
    messagingSenderId: '864533928664',
    projectId: 'to-do-list-c9aaf',
    authDomain: 'to-do-list-c9aaf.firebaseapp.com',
    storageBucket: 'to-do-list-c9aaf.firebasestorage.app',
    measurementId: 'G-22DQNFJG28',
  );
}
